<a href="https://colab.research.google.com/github/abdul4rehman215/AI-Advanced-Course-Portfolio/blob/main/08-deep-learning-foundations-and-artificial-neural-networks/notebooks/lec26_prerequiste_NumPy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Tutorial: From Scalars to Tensors

NumPy (Numerical Python) is the fundamental package for scientific computing in Python. It provides a high-performance multidimensional array object and tools for working with these arrays.

In [ ]:
import numpy as np
print(f"NumPy version: {np.__version__}")

NumPy version: 2.0.2


## 1. Scalars (0-D Arrays)
An array with a single value is considered a 0-dimensional array or a scalar.

In [ ]:
scalar = np.array(42)

print("Scalar:", scalar)
print("Shape:", scalar.shape)
print("Type:", type(scalar))

Scalar: 42
Shape: ()
Type: <class 'numpy.ndarray'>


## 2. Vectors (1-D Arrays)
Vectors are 1D arrays. We can create them using helper functions or from Python lists.

In [ ]:
# Create a 1D array of 3 zeros
zeros_vec = np.zeros(3)
print("Zeros Vector:", zeros_vec)

# Create a 1D array of 3 ones
ones_vec = np.ones(3)
print("Ones Vector:", ones_vec)

# Custom 1D array and slicing
custom_vec = np.array([10, 20, 30, 40, 50])
print("Custom Vector:", custom_vec)
print("First two elements [0:2]:", custom_vec[0:2])
print("Elements from index 1 onwards [1:]:", custom_vec[1:])

Zeros Vector: [0. 0. 0.]
Ones Vector: [1. 1. 1.]
Custom Vector: [10 20 30 40 50]
First two elements [0:2]: [10 20]
Elements from index 1 onwards [1:]: [20 30 40 50]


## 3. Matrices (2-D Arrays)
Matrices are 2D arrays consisting of rows and columns.

In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])

print("Matrix:\n", matrix)
print("Shape:", matrix.shape)

# Accessing a specific element (row 0, column 1)
element = matrix[0, 1]
print("Element at row 0, col 1:", element)

Matrix:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Element at row 0, col 1: 2


## 4. Tensors (3-D and Higher)
3D arrays can be thought of as a collection of matrices. They represent data with depth, rows, and columns.

In [ ]:
tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("3D Tensor:\n", tensor)
print("Shape:", tensor.shape) # Output format: (Depth, Rows, Columns)

3D Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)


## 5. Reshaping Arrays
Reshaping means changing the layout of the array without changing its data. The total number of elements must remain the same.

In [ ]:
vec = np.arange(12) # Creates [0, 1, ..., 11]
print("Original Vector:", vec)

# Reshape to 3x4 matrix
matrix_3x4 = vec.reshape(3, 4)
print("Reshaped (3,4):\n", matrix_3x4)

# Reshape to 2x2x3 tensor
tensor_3d = vec.reshape(2, 2, 3)
print("Reshaped (2,2,3):\n", tensor_3d)

try:
    # This will fail because 12 elements cannot fit into a 5x5 (25 slots) shape
    vec.reshape(5, 5)
except ValueError as e:
    print("\nError demonstrated:", e)

Original Vector: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped (3,4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped (2,2,3):
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]

Error demonstrated: cannot reshape array of size 12 into shape (5,5)
